### ISSUE TITLE
unable to import any csv (500 internal server error)

### ISSUE THREAD

**Issue by anandakmanchi** [leovitch/redmine_importer#10]
I am unable to import any csv file including the ones provided in test/samples
when i try to choose any csv file and click "upload file", it throws up the 500 error page

i am using Bitnami Redmine Stack 1.2.1 on windows

here is the log detail
Processing ImporterController#match (for 172.30.5.20 at 2011-12-22 16:56:44) [POST]
  Parameters: {"encoding"=>"U", "commit"=>"Upload File", "project_id"=>"3", "action"=>"match", "authenticity_token"=>"SCH+utQujAeY1uAENk5pRfZUYz7jJZei4NNMeV98ud0=", "controller"=>"importer", "file"=>#File:C:/WINDOWS/Temp/RackMultipart20111222-6164-f8i3pp-0, "splitter"=>",", "wrapper"=>"\""}

ArgumentError (comparison of Array with Array failed):
  vendor/plugins/redmine_importer/app/controllers/importer_controller.rb:71:in `sort!'
  vendor/plugins/redmine_importer/app/controllers/importer_controller.rb:71:in`match'
  config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'

Rendering C:/Program Files/BitNami Redmine Stack/apps/redmine/public/500.html (500 Internal Server Error)

**Comment by leovitch** [comment]
Hi ananda,

It's hard to say since I don't have a Windows machine at the moment, but it's a problem with the installation.  That line of code should just be sorting a bunch of constants, i.e., it hasn't read any input data yet.

It is fetching localized strings though.  What language is your Redmine installation set to?

Leo
