### ISSUE TITLE
Problem after upgrading Redmine from 1.3.2.1 to 1.4.1.0

### ISSUE THREAD

**Issue by lbushby** [leovitch/redmine_importer#26]
Hi,

Firstly, many thanks for a great plugin.  Being able to import data is key for me and the latest version of your plugin works very well. 

My issue: I recently upgraded Redmine from 1.3.2.1 to 1.4.1.0 and when I tried to view a project that was previously ok I got an 'Internal error' page.  I checked the production log and found this error

```
Processing ProjectsController#show (for 200.0.0.77 at 2012-04-27 12:00:36) [GET]
  Parameters: {"action"=>"show", "controller"=>"projects", "id"=>"test1"}
Rendering template within layouts/base
Rendering projects/show

ActionView::TemplateError (No route matches {:action=>"index", :project_id=>#<Project id: 1, name: "SomeProject", description: "SomeProject main development", homepage: "", is_public: false, parent_id: nil, created_on: "2012-04-10 12:40:39", updated_on: "2012-04-12 12:18:33", identifier: "test1", status: 1, lft: 3, rgt: 4>, :controller=>"importer"}) on line #57 of app/views/layouts/base.html.erb:
54: 
55:     <% if display_main_menu?(@project) %>
56:     <div id="main-menu">
57:         <%= render_main_menu(@project) %>
58:     </div>
59:     <% end %>
60: </div>

    lib/redmine/menu_manager.rb:150:in `render_single_menu_node'
    lib/redmine/menu_manager.rb:102:in `render_menu_node'
    lib/redmine/menu_manager.rb:91:in `render_menu'
    lib/redmine/menu_manager.rb:168:in `menu_items_for'
    lib/redmine/menu_manager.rb:165:in `each'
    lib/redmine/menu_manager.rb:165:in `menu_items_for'
    lib/redmine/menu_manager.rb:90:in `render_menu'
    lib/redmine/menu_manager.rb:80:in `render_main_menu'
    app/views/layouts/base.html.erb:57
    app/controllers/projects_controller.rb:168:in `show'
    config/initializers/mongrel_cluster_with_rails_211_fix.rb:62:in `dispatch_cgi'

Rendering C:/Program Files/BitNami Redmine Stack 1.4.1/apps/redmine/public/500.html (500 Internal Server Error)
```

I'm pretty clueless when it comes to Ruby but the error seemed similar to [this](http://www.redmine.org/issues/9778) Redmine issue so without really understanding what I was doing I added a new file '...\plugins\redmine_importer\config\routes.rb' with these contents:

```
ActionController::Routing::Routes.draw do |map|
  map.connect ':controller/:action/:id'
end
```

I then restarted redmine and the error no longer occurs.  I'm hoping you might understand what the actual problem was and produce a 'correct' fix at some point but in the meantime this information might be useful for anyone else who encounters this issue.

**Comment by lbushby** [comment]
Shortly after clicking 'submit' I realised that this is probably the same as issue [24](https://github.com/leovitch/redmine_importer/issues/24) - sorry for the duplication

**Comment by lbushby** [comment]
(I've closed this since it's a duplicate and I'll comment on issue 24 instead)
